<?xml version="1.0"?>

<!DOCTYPE client [
    <!--
        xml config file to describe client program
        The values of "name" must be unique
    -->

    <!-- one config and one MainWindow, one or more detectors -->
    <!ELEMENT client (config, MainWindow, detector+)>
   
    <!-- config has one server -->
    <!-- server has one host and one port -->
    <!ELEMENT config (server)>
    <!ELEMENT server (host, port)>
    <!ELEMENT host (#PCDATA)>
    <!ELEMENT port (#PCDATA)>
    
    <!-- MainWindow must contain name, title, width, height, openlist, reconnect -->
    <!ELEMENT MainWindow (name, title, width, height, snapshotpath, autosaverate, snapshotpathonline, autosaverateonline, openlist, reconnect)>
    
    <!-- one or more windows for each detector -->
    <!ELEMENT detector (name, title, window+)>
    
    <!-- window must contain name, title, tabbed -->
    <!ELEMENT window (name, title, tabbed, canvas*, tab*)>
    
    <!-- each tab has one or more canvases -->
    <!ELEMENT tab (name, title, canvas+)>
    
    <!-- canvas must contain name, title, width, height, splitted, nx, ny -->
    <!-- one or more histograms -->
    <!ELEMENT canvas (name, width, height, splitted, nx, ny, histogram+)>
    
    <!-- histogram must contain name, title, subpad -->
    <!-- one or more canvases -->
    <!ELEMENT histogram (name, type, subpad)>
    
    
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT width (#PCDATA)>
    <!ELEMENT height (#PCDATA)>
    <!ELEMENT snapshotpath (#PCDATA)>
    <!ELEMENT autosaverate (#PCDATA)>
    <!ELEMENT snapshotpathonline (#PCDATA)>
    <!ELEMENT autosaverateonline (#PCDATA)>
    <!ELEMENT openlist (#PCDATA)>
    <!ELEMENT reconnect (#PCDATA)>
    <!ELEMENT tabbed (#PCDATA)>
    <!ELEMENT splitted (#PCDATA)>
    <!ELEMENT nx (#PCDATA)>
    <!ELEMENT ny (#PCDATA)>
    <!ELEMENT type (#PCDATA)>
    <!ELEMENT subpad (#PCDATA)>
]>

<client>
    
    <!-- program configuration -->
    <config>
        <server>
            <host>lxhadeb06.gsi.de</host>
            <port>9876</port>
        </server>
    </config>
    
    
    <!-- configuration for main window -->
    <MainWindow>
        <name>HADESMonitoring</name>
        <title>HADES Monitoring</title>
        <width>250</width>
        <height>550</height>
        <snapshotpath>/home/hades-qa/online/apr12/pics/</snapshotpath>
        <autosaverate>60</autosaverate> 
        <snapshotpathonline>/home/hades-qa/online/apr14/pics/png/</snapshotpathonline>
        <autosaverateonline>3</autosaverateonline> 
        <!-- openlist>all</openlist> -->
       <!-- <openlist>Main,Start,RICH,MDC,MDCTimes,MDCTimesRaw,TOF,RPC,WALL,SHOWER,Physics</openlist> -->
       <openlist>Main,Start,RICH,MDC,MDCTimes,MDCTimesRaw,TOF,RPC,WALL,SHOWER,Physics,PionTracker,Hodo</openlist>
       <!--<openlist>Main,Hodo,PionTracker</openlist>-->
       <!-- <openlist>all</openlist> -->
        <reconnect>2</reconnect> 
    </MainWindow>


    <!-- detector configuration -->
    <detector>
        <name>Main</name>
        <title>Main</title>
        <window>
            <name>Main</name>
            <title>Main</title>
            <tabbed>true</tabbed>
            <tab>
                <name>Trigger</name>
                <title>Trigger</title>
                <canvas>
                   <name>MainTrigger</name>
                   <width>800</width>
                   <height>600</height>
                   <splitted>true</splitted>
                   <nx>3</nx>
                   <ny>2</ny>
                   <histogram>
                       <name>hLatch_Norm</name>
                       <type>single</type>
                       <subpad>1</subpad>
                   </histogram>
                   <histogram>
                       <name>hStart_EventID</name>
                       <type>single</type>
                       <subpad>2</subpad>
                   </histogram>
                   <histogram>
                       <name>hLatch_Mult</name>
                       <type>single</type>
                       <subpad>3</subpad>
                   </histogram>
                   <histogram>
                       <name>hRpcTMultiplicity</name>
                       <type>single</type>
                       <subpad>4</subpad>
                   </histogram>
                   <histogram>
                        <name>hTofMultiplicity</name>
                        <type>single</type>
                        <subpad>5</subpad>
                   </histogram>
                   <histogram>
                        <name>hRpcTofMultiplicity</name>
                        <type>single</type>
                        <subpad>6</subpad>
                   </histogram>
                </canvas>
            </tab>
            <tab>
                <name>TriggerTrend</name>
                <title>TriggerTrend</title>
                <canvas>
                   <name>MainTriggerTrend</name>
                   <width>800</width>
                   <height>600</height>
                   <splitted>true</splitted>
                   <nx>2</nx>
                   <ny>2</ny>
                   <histogram>
                       <name>hLatch_Trend</name>
                       <type>array:0:11</type>
                       <subpad>1</subpad>
                   </histogram>
                   <histogram>
                       <name>hLatch_Trend</name>
                       <type>array:0:12</type>
                       <subpad>2</subpad>
                   </histogram>
                   <histogram>
                       <name>hLatch_Trend</name>
                       <type>array:0:13</type>
                       <subpad>3</subpad>
                   </histogram>
                   <histogram>
                       <name>hLatch_Trend</name>
                       <type>array:0:14</type>
                       <subpad>4</subpad>
                   </histogram>
                </canvas>
            </tab>
            <tab>
                <name>PTScaler</name>
                <title>PTScaler</title>
                <canvas>
                   <name>MainPTScaler</name>
                   <width>800</width>
                   <height>600</height>
                   <splitted>true</splitted>
                   <nx>4</nx>
                   <ny>3</ny>
                   <histogram>
                       <name>hScalers_Trend</name>
                       <type>array:0:28</type>
                       <subpad>1</subpad>
                   </histogram>
                   <histogram>
                       <name>hScalers_Trend</name>
                       <type>array:0:29</type>
                       <subpad>2</subpad>
                   </histogram>
                   <histogram>
                       <name>hScalers_Trend</name>
                       <type>array:0:30</type>
                       <subpad>3</subpad>
                   </histogram>
                   <histogram>
                       <name>hScalers_Trend</name>
                       <type>array:0:31</type>
                       <subpad>4</subpad>
                   </histogram>
                   <histogram>
                       <name>hScalers_Trend</name>
                       <type>array:0:43</type>
                       <subpad>5</subpad>
                   </histogram>
                   <histogram>
                       <name>hScalers_Trend</name>
                       <type>array:0:44</type>
                       <subpad>6</subpad>
                   </histogram>
                   <histogram>
                       <name>hScalers_Trend</name>
                       <type>array:0:45</type>
                       <subpad>7</subpad>
                   </histogram>
                   <histogram>
                       <name>hScalers_Trend</name>
                       <type>array:0:46</type>
                       <subpad>8</subpad>
                   </histogram>
                   <histogram>
                       <name>hScalers_Trend</name>
                       <type>array:0:58</type>
                       <subpad>9</subpad>
                   </histogram>
                   <histogram>
                       <name>hScalers_Trend</name>
                       <type>array:0:59</type>
                       <subpad>10</subpad>
                   </histogram>
                   <histogram>
                       <name>hScalers_Trend</name>
                       <type>array:0:60</type>
                       <subpad>11</subpad>
                   </histogram>
                   <histogram>
                       <name>hScalers_Trend</name>
                       <type>array:0:61</type>
                       <subpad>12</subpad>
                   </histogram>
                </canvas>
            </tab>
            <tab>
                <name>TRBNetDebugInfo</name>
                <title>TRBNetDebugInfo</title>
                <canvas>
                   <name>MainTRBNetDebugInfo</name>
                   <width>800</width>
                   <height>600</height>
                   <splitted>true</splitted>
                   <nx>6</nx>
                   <ny>5</ny>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:0</type>
                       <subpad>1</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:1</type>
                       <subpad>3</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:2</type>
                       <subpad>4</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:3</type>
                       <subpad>5</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:4</type>
                       <subpad>6</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:5</type>
                       <subpad>7</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:6</type>
                       <subpad>8</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:7</type>
                       <subpad>9</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:8</type>
                       <subpad>10</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:9</type>
                       <subpad>11</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:10</type>
                       <subpad>12</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:11</type>
                       <subpad>13</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:12</type>
                       <subpad>14</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:13</type>
                       <subpad>15</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:14</type>
                       <subpad>16</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:15</type>
                       <subpad>17</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:16</type>
                       <subpad>18</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:17</type>
                       <subpad>19</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:18</type>
                       <subpad>20</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:19</type>
                       <subpad>21</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:20</type>
                       <subpad>22</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:21</type>
                       <subpad>23</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:22</type>
                       <subpad>24</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:23</type>
                       <subpad>25</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:24</type>
                       <subpad>26</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:25</type>
                       <subpad>27</subpad>
                   </histogram>
                   <histogram>
                       <name>hTrbNetDebug</name>
                       <type>array:0:26</type>
                       <subpad>28</subpad>
                   </histogram>
                   </canvas>
            </tab>
        </window>
    </detector>
    
    <detector>
        <name>Hodo</name>
        <title>Hodo</title>
        <window>
            <name>Hodo</name>
            <title>Hodo</title>
            <tabbed>true</tabbed>
            <tab>
                <name>MultHodo</name>
                <title>Mult</title>
                <canvas>
                   <name>HodoMult</name>
                   <width>800</width>
                   <height>600</height>
                   <splitted>true</splitted>
                   <nx>2</nx>
                   <ny>2</ny>
                   <histogram>
                       <name>hhodoraw</name>
                       <type>array:0:0</type>
                       <subpad>1</subpad>
                   </histogram>
                   <histogram>
                       <name>hhodoraw</name>
                       <type>array:0:1</type>
                       <subpad>2</subpad>
                   </histogram>
                </canvas>
            </tab>
            <tab>
                <name>TimeHodo</name>
                <title>Time</title>
                <canvas>
                   <name>HodoTime</name>
                   <width>800</width>
                   <height>600</height>
                   <splitted>true</splitted>
                   <nx>1</nx>
                   <ny>1</ny>
                   <histogram>
                       <name>hodorawstriptime</name>
                       <type>single</type>
                       <subpad>1</subpad>
                   </histogram>
                </canvas>
            </tab>
        </window>
    </detector>

    <detector>
        <name>PionTracker</name>
        <title>PionTracker</title>
        <window>
            <name>PionTrackerRaw</name>
            <title>PionTracker_Raw</title>
            <tabbed>true</tabbed>
            <tab>
                <name>RawMult</name>
                <title>Mult</title>
                <canvas>
                   <name>Mult</name>
                   <width>800</width>
                   <height>600</height>
                   <splitted>true</splitted>
                   <nx>2</nx>
                   <ny>2</ny>
                   <histogram>
                       <name>hPTRawMult</name>
                       <type>array:0:0</type>
                       <subpad>1</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawMult</name>
                       <type>array:0:1</type>
                       <subpad>2</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawMult</name>
                       <type>array:0:2</type>
                       <subpad>3</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawMult</name>
                       <type>array:0:3</type>
                       <subpad>4</subpad>
                   </histogram>
                </canvas>
            </tab>
            <tab>
                <name>RawTS</name>
                <title>TS</title>
                <canvas>
                   <name>TS</name>
                   <width>800</width>
                   <height>600</height>
                   <splitted>true</splitted>
                   <nx>2</nx>
                   <ny>2</ny>
                   <histogram>
                       <name>hPTRawTimeStamp</name>
                       <type>array:0:0</type>
                       <subpad>1</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawTimeStamp</name>
                       <type>array:0:1</type>
                       <subpad>2</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawTimeStamp</name>
                       <type>array:0:2</type>
                       <subpad>3</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawTimeStamp</name>
                       <type>array:0:3</type>
                       <subpad>4</subpad>
                   </histogram>
                </canvas>
            </tab>
            <tab>
                <name>RawStrip</name>
                <title>Strip</title>
                <canvas>
                   <name>Strip</name>
                   <width>800</width>
                   <height>600</height>
                   <splitted>true</splitted>
                   <nx>2</nx>
                   <ny>2</ny>
                   <histogram>
                       <name>hPTRawStrip</name>
                       <type>array:0:0</type>
                       <subpad>1</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawStrip</name>
                       <type>array:0:1</type>
                       <subpad>2</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawStrip</name>
                       <type>array:0:2</type>
                       <subpad>3</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawStrip</name>
                       <type>array:0:3</type>
                       <subpad>4</subpad>
                   </histogram>
                </canvas>
            </tab>
            <tab>
                <name>RawPileup</name>
                <title>Pileup</title>
                <canvas>
                   <name>Pileup</name>
                   <width>800</width>
                   <height>600</height>
                   <splitted>true</splitted>
                   <nx>2</nx>
                   <ny>2</ny>
                   <histogram>
                       <name>hPTRawPileup</name>
                       <type>array:0:0</type>
                       <subpad>1</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawPileup</name>
                       <type>array:0:1</type>
                       <subpad>2</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawPileup</name>
                       <type>array:0:2</type>
                       <subpad>3</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawPileup</name>
                       <type>array:0:3</type>
                       <subpad>4</subpad>
                   </histogram>
                </canvas>
            </tab>
            <tab>
                <name>RawOverflow</name>
                <title>Overflow</title>
                <canvas>
                   <name>Overflow</name>
                   <width>800</width>
                   <height>600</height>
                   <splitted>true</splitted>
                   <nx>2</nx>
                   <ny>2</ny>
                   <histogram>
                       <name>hPTRawOverflow</name>
                       <type>array:0:0</type>
                       <subpad>1</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawOverflow</name>
                       <type>array:0:1</type>
                       <subpad>2</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawOverflow</name>
                       <type>array:0:2</type>
                       <subpad>3</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawOverflow</name>
                       <type>array:0:3</type>
                       <subpad>4</subpad>
                   </histogram>
                </canvas>
            </tab>
            <tab>
                <name>RawADCStrip</name>
                <title>ADC-Strip</title>
                <canvas>
                   <name>ADCStrip</name>
                   <width>800</width>
                   <height>600</height>
                   <splitted>true</splitted>
                   <nx>2</nx>
                   <ny>2</ny>
                   <histogram>
                       <name>hPTRawStripADC</name>
                       <type>array:0:0</type>
                       <subpad>1</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawStripADC</name>
                       <type>array:0:1</type>
                       <subpad>2</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawStripADC</name>
                       <type>array:0:2</type>
                       <subpad>3</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawStripADC</name>
                       <type>array:0:3</type>
                       <subpad>4</subpad>
                   </histogram>
                </canvas>
            </tab>
            <tab>
                <name>RawTSStrip</name>
                <title>TS-Strip</title>
                <canvas>
                   <name>TSStrip</name>
                   <width>800</width>
                   <height>600</height>
                   <splitted>true</splitted>
                   <nx>2</nx>
                   <ny>2</ny>
                   <histogram>
                       <name>hPTRawStripTimeStamp</name>
                       <type>array:0:0</type>
                       <subpad>1</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawStripTimeStamp</name>
                       <type>array:0:1</type>
                       <subpad>2</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawStripTimeStamp</name>
                       <type>array:0:2</type>
                       <subpad>3</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawStripTimeStamp</name>
                       <type>array:0:3</type>
                       <subpad>4</subpad>
                   </histogram>
                </canvas>
            </tab>
            <tab>
                <name>RawXY</name>
                <title>X-Y</title>
                <canvas>
                   <name>XY</name>
                   <width>800</width>
                   <height>600</height>
                   <splitted>true</splitted>
                   <nx>2</nx>
                   <ny>1</ny>
                   <histogram>
                       <name>hPTRawXY</name>
                       <type>array:0:0</type>
                       <subpad>1</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawXY</name>
                       <type>array:0:1</type>
                       <subpad>2</subpad>
                   </histogram>
                </canvas>
            </tab>
            <tab>
                <name>RawPTHodoDt</name>
                <title>Pt-Hodo-dT</title>
                <canvas>
                   <name>RawPTHodoDt</name>
                   <width>800</width>
                   <height>600</height>
                   <splitted>true</splitted>
                   <nx>2</nx>
                   <ny>2</ny>
                   <histogram>
                       <name>hPTRawHodoDt</name>
                       <type>array:0:0</type>
                       <subpad>1</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawHodoDt</name>
                       <type>array:0:1</type>
                       <subpad>2</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawHodoDt</name>
                       <type>array:0:2</type>
                       <subpad>3</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTRawHodoDt</name>
                       <type>array:0:3</type>
                       <subpad>4</subpad>
                   </histogram>
                </canvas>
            </tab>
        </window>

        <window>
            <name>PionTrackerCal</name>
            <title>PionTracker_Cal</title>
            <tabbed>true</tabbed>
<!--            <tab>
                <name>CalMult</name>
                <title>Mult</title>
                <canvas>
                   <name>CalMult</name>
                   <width>800</width>
                   <height>600</height>
                   <splitted>true</splitted>
                   <nx>2</nx>
                   <ny>2</ny>
                   <histogram>
                       <name>hPTCalMult</name>
                       <type>array:0:0</type>
                       <subpad>1</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTCalMult</name>
                       <type>array:0:1</type>
                       <subpad>2</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTCalMult</name>
                       <type>array:0:2</type>
                       <subpad>3</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTCalMult</name>
                       <type>array:0:3</type>
                       <subpad>4</subpad>
                   </histogram>
                </canvas>
            </tab>-->
            <tab>
                <name>CalTS</name>
                <title>TS</title>
                <canvas>
                   <name>CalTS</name>
                   <width>800</width>
                   <height>600</height>
                   <splitted>true</splitted>
                   <nx>2</nx>
                   <ny>2</ny>
                   <histogram>
                       <name>hPTCalTimeStamp</name>
                       <type>array:0:0</type>
                       <subpad>1</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTCalTimeStamp</name>
                       <type>array:0:1</type>
                       <subpad>2</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTCalTimeStamp</name>
                       <type>array:0:2</type>
                       <subpad>3</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTCalTimeStamp</name>
                       <type>array:0:3</type>
                       <subpad>4</subpad>
                   </histogram>
                </canvas>
            </tab>
<!--            <tab>
                <name>CalStrip</name>
                <title>Strip</title>
                <canvas>
                   <name>CalStrip</name>
                   <width>800</width>
                   <height>600</height>
                   <splitted>true</splitted>
                   <nx>2</nx>
                   <ny>2</ny>
                   <histogram>
                       <name>hPTCalStrip</name>
                       <type>array:0:0</type>
                       <subpad>1</subpad>
                   </histogram>
                   <histogram>
                       <name>hPTCalStrip</name>